default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

# production:
#   <<: *default
#   adapter: postgresql
#   encoding: unicode
#   database: myapp_production
#   username: postgres
#   password: <%= ENV.fetch("DATABASE_PASSWORD") {'postgres'} %>
